name: flutter_builder
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  google_fonts: ^2.2.0
  get: ^4.3.8
  get_it: ^7.2.0
  cyclop: ^0.5.2
  encrypt: ^5.0.1
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+4
  file_picker: ^5.0.1
  connectivity_plus: ^2.3.6+1
  device_preview: ^1.1.0
  flutter_reorderable_list: ^1.1.0
  equatable: ^2.0.3
  firedart: ^0.9.0+1
  win_toast: ^0.0.2
  intl: ^0.17.0
  resizable_widget: ^1.0.5
  # TODO  use multi_split_view: ^2.1.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.9
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
#  firebase_core_desktop: ^0.1.1-dev.0
#  firebase_auth_desktop: ^0.1.1-dev.0
  cloud_firestore: ^3.1.6
#  firebase_storage: ^10.2.5
  fluttertoast: ^8.0.9
  archive: ^3.3.0
  flutter_overlay_loader: ^1.0.3
  shimmer: ^2.0.0
  code_text_field: ^1.0.2
  dart_style: ^2.2.2
  pull_to_refresh: ^2.0.0
  url_strategy: ^0.2.0
  flutter_svg: ^1.1.4
  http: ^0.13.4
  keyboard_event: ^0.3.2
  flutter_slider_drawer: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  file_saver: ^0.1.1
  permission_handler: ^10.0.0
  flutter_json_viewer: ^1.0.1
  json_editor: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/icons/
  uses-material-design: true

