name: flutter_builder
description: A Low-code Platform.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.2.1
#  get: ^4.3.8
  url_launcher: ^6.1.11
  get_it: ^7.2.0
#  flutter_colorpicker: ^1.0.3
  encrypt: ^5.0.1
  flex_color_picker: ^3.5.0
  flutter_switch: ^0.3.2
  image_picker: ^1.0.1
  connectivity_plus: ^6.0.2
  equatable: ^2.0.3
  intl: ^0.18.0
  resizable_widget: ^1.0.5
  chat_gpt_sdk: ^3.1.5
#  ollama: ^1.0.4
  flutter_dotenv: ^5.2.1
  device_preview:
    path: device_preview

  # TODO  use multi_split_view: ^2.1.0

#  firebase_core: ^2.16.0
#  firebase_auth: ^4.10.0

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

#    path: packages/cloud_firestore


  firebase_storage: ^12.4.7

  shared_preferences: ^2.0.13
#  font_awesome_flutter: ^10.1.0
  #  firebase_core_desktop: ^0.1.1-dev.0
  #  firebase_auth_desktop: ^0.1.1-dev.0

  #  firebase_storage: ^10.2.5
#  fluttertoast: ^8.0.9
  archive: ^3.3.0
  shimmer: ^3.0.0
  code_text_field: ^1.1.0
  dart_style: ^2.2.2
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.7
  http: 1.3.0
  collection: ^1.18.0
#  keyboard_event: ^0.3.2

  file_saver: ^0.2.6
  permission_handler: ^11.3.0
  json_view: ^0.4.0
#  json_editor: ^0.0.8
#  textfield_search: ^0.10.0
#  touchable: ^1.0.2
  #  sembast: ^3.3.1
#  external_path: ^1.0.3
  loading_indicator: ^3.1.0
  dotted_border: ^2.0.0+3
  dio: ^5.0.0
  sembast_web: ^2.0.1+1
#  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.1.1
  ionicons_named: ^1.3.0
  flutter_screenutil: ^5.6.0
  loader_overlay: ^5.0.0
  provider: ^6.0.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  image: ^4.0.10
  pasteboard: ^0.2.0
  native_context_menu: ^0.2.2+5
  lottie: ^3.0.0
  retrofit: ^4.0.1
  uni_links: ^0.5.1
  uni_links_desktop: ^0.1.6
#  fluent_ui: ^4.6.1
  flutter_animate: ^4.1.1+1
#  appwrite: ^12.0.1
  process_run: ^1.2.0
  path_provider: ^2.1.3
  rxdart: ^0.28.0
  file_picker: ^8.0.7
#  recase: ^4.1.0
  app_links: ^6.3.2
  google_generative_ai: ^0.4.7
#  dart_eval: ^0.7.9
  fvb_processor:
    path: fvb_processor

  flutter_localizations:
    sdk: flutter
dependency_overrides:
  intl: 0.17.0
#  http: 1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^9.1.1

flutter:

  assets:
    - assets/icons/
    - assets/components/
    - assets/lottie/
    - assets/.env

  uses-material-design: true
flutter_intl:
  enabled: true
