// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwzU0FyuCsD-pDX4Vvt3oHth4KdNWwnw',
    appId: '1:585919568929:web:20c22834346fe6ad98d760',
    messagingSenderId: '585919568929',
    projectId: 'flutter-visual-builder-staging',
    authDomain: 'flutter-visual-builder-staging.firebaseapp.com',
    storageBucket: 'flutter-visual-builder-staging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcKrtGV-8p-NxhkY_G6bQfbL6Um1CHYY',
    appId: '1:585919568929:android:5c13ac1472f8d02e98d760',
    messagingSenderId: '585919568929',
    projectId: 'flutter-visual-builder-staging',
    storageBucket: 'flutter-visual-builder-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8WzT_9MxjjCyXy8eOmtDsC7VfkED69s',
    appId: '1:585919568929:ios:e3f9f52703b6a8f498d760',
    messagingSenderId: '585919568929',
    projectId: 'flutter-visual-builder-staging',
    storageBucket: 'flutter-visual-builder-staging.appspot.com',
    iosClientId:
        '585919568929-v6la11jl3ajegj3sbrl6659ltsoj75t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn8WzT_9MxjjCyXy8eOmtDsC7VfkED69s',
    appId: '1:585919568929:ios:d0868c04960f2f0498d760',
    messagingSenderId: '585919568929',
    projectId: 'flutter-visual-builder-staging',
    storageBucket: 'flutter-visual-builder-staging.appspot.com',
    iosClientId:
        '585919568929-s7k340ebuf1cp29flvhnpfeocsvtoci9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVisualBuilder',
  );
}
