name: fvb_processor
description: A Processor Module of the FlutterPilot Low code Platform.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  flutter_bloc: ^8.1.3
  http: ^1.2.1
  intl: ^0.18.0
  shared_preferences: ^2.0.13
  equatable: ^2.0.5
  collection: ^1.18.0
  flutter_builder:
    path: ../../flutter_builder

dependency_overrides:
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  module:
    androidX: true
    androidPackage: com.example.fvb_processor
    iosBundleIdentifier: com.example.fvbProcessor
